const tripsData =[{id: 0, star: 5, category: "cultural trip", checkbox:'culturalTrip', name:"In the flow of life", duration: "4 days", date: 'July 2nd, 2021', price: 990, description: 'You encounter the Dionysian at a preferred place of a vineyard. The picturesque hotel "Weinberg Schlösschen" with its fabulous location in the vineyard invites you to philosophical and culinary excursions.', image: 'https://img.theculturetrip.com/450x/smart/wp-content/uploads/2018/05/urzig-2066628_1280.jpg'}, 
{id:1, star: 4, category: "Cultural trip", checkbox:'culturalTrip', name: 'Munster in Westphalia', duration: "4 days", date: 'September 17, 2021', price: 990, description: 'Discover the "most livable city in Germany" between 1228 years of history and the dawn of modernity as an internationally ambitious bicycle city, educational metropolis and science location.', image: 'https://www.tourism.de/wp-content/uploads/2017/05/Munster-St-Paulus-Dom-640x427.jpg'}, 
{id:2, star: 4, category: "Cultural trip", checkbox:'culturalTrip', name: 'Leipzig - Musical Architecture Tour', duration: "5 days", date: 'June 10, 2021', price: 1290, description: 'Leipzig is cool - according to the New York Times the new “place to see”. But the music, publishing, trade fair and the city has not just been reinventing itself since yesterday.', image: 'https://www.parkhotelleipzig.de/wp-content/uploads/2016/09/park-hotel-leipzig-oper.jpg'}, 
{id:3, star: 5, category: "Cultural trip", checkbox:'culturalTrip',name: 'Rhön - The wisdown of the forests', duration: "4 days", date: 'November 10, 2021', price: 1050, description: 'The wisdom of the forests speaks many languages. We walk on the traces of the sagas and legends that surround the forests of the Rhön. We enjoy the rustling of the treetops', image: 'https://www.rhoentourist.de/wp-content/uploads/2020/06/basaltsee-tintenfass-rhoen.jpg'}, 
{id:4, star: 5, category: "Music trip", checkbox:'musicTrip', name: 'Classic sounds in Dresden', duration: "3-4 days", date: 'October 10, 2021', price: 349, description: 'Experience one of the most beautiful cities in Germany with its famous sights such as the Zwinger, the Elbterrassen or the Residenzschloss. Historical splendid buildings form a unique city center that also houses art treasures of significant value.', image: 'https://dmg.dresden.de/media/bilder/dmg/infoservice/dir-1/1005_Musik.jpg'}, 
{id:5, star: 4, category: "Music trip", checkbox:'musicTrip', name: 'Schloss Elmau - Verbier Festival as a guest', duration: "6 days", date: 'August 10, 2021', price: 2349, description: 'Located at the foot of the Wetterstein Mountains, near Garmisch-Partenkirchen, the five-star Hotel Schloss Elmau promises musical delights, embedded in the spring and the silence of the alpine nature.', image: 'https://www.merkur.de/bilder/2020/04/03/13640198/535775578-am-fuss-wettersteingebirges-gelegen-schloss-elmau-NDeRvAMYYea.jpg'}, 
{id:6, star: 3, category: "Music trip",  checkbox:'musicTrip', name: 'Musical spring in Berlin', duration: "4 days", date: 'June 29, 2021', price: 1420, description: 'The Komische Oper Berlin - long known for its dynamic soloists, its committed choir, its flexible orchestra and its large repertoire of lively productions - is putting three works full of verve and lightness on the program for one spring weekend', image: 'https://dlmgvfu16d6d1.cloudfront.net/wp-content/uploads/2017/03/17153114/0001ADAMIK__6107023.jpg'}, 
{id:7, star: 4, category: "Nature & active",  checkbox:'natureTrip', name: 'With the e-bike across the Alps', duration: "9 days", date: 'November 9, 2021', price: 1985, description: 'Driving with electric power: through the Munich lake district, across the foothills of the Alps into the Alps. You cycle at the foot of the Zugspitze to Austria and through the Inn Valley into the high Alps.', image: 'https://s14761.pcdn.co/wp-content/uploads/sites/2/2019/04/E-MOUNTAINBIKE-Alpencross-Guide-015.jpg'}, 
{id:8, star: 5, category: "Nature & active", checkbox:'natureTrip', name: 'Hiking trip to the mysteries of the Vulkanefel', duration: "5 days", date: 'May 9, 2021', price: 730, description: 'The idiosyncratic beauty of the Eifel has already inspired the romantics. But the Vulkaneifel offers much more than just magical landscapes: it also tells of how the earth came into being.', image: 'https://thumbor.forbes.com/thumbor/960x0/https%3A%2F%2Fblogs-images.forbes.com%2Fannabel%2Ffiles%2F2017%2F09%2FMTS_Mont-Blanc_4-1200x900.jpg'}, 
{id:9, star: 4, category: "Nature & active", checkbox:'natureTrip', name: 'Cycling in the footsteps of the "Blue Rider" ', duration: "6 days", date: 'June 19, 2021', price: 1490, description: 'Immerse yourself in the world of the great Expressionists: the bike tour takes you on idyllic paths from Munich to the original painting sites and homes of the great masters - through a landscape that was both inspiration and living environment.', image: 'https://www.nationalparks.nsw.gov.au/-/media/npws/images/parks/blue-mountains-national-park/katoomba-area/andersons-trail/andersons-trail-01.jpg?rev=6701e1a38a314d7d829e67320e634e92'}, 
{id:10, star: 4, category: "Ship && Train", checkbox:'shipTrip', name: 'From Hamburg to New York', duration: "11 days", date: 'August 19, 2021', price: 1800, description: 'To travel across the Atlantic once in a lifetime ... Has that always been your travel dream? You can make this dream come true in summer 2021 - on board the »Queen Mary 2«, the last real ocean liner that still operates on the classic route between Europe and America.', image: 'https://www.brooklyncruiseguide.com/img/queen-mary-2-ny.jpg'}, 
{id:11, star: 3, category: "Ship && Train", checkbox:'shipTrip', name: 'German-Czech history on the Elbe and Vltava', duration: "12 days", date: 'September 19, 2021', price: 2295, description: 'Your river journey on the Elbe and Vltava begins within sight of the Elbphilharmonie in Hamburg and leads over Magdeburg, Dresden, Meißen, Melnik and ends on the doorstep of the Hradschin - past clear lakes, historical places and imposing castles.', image: 'https://cdn.tourradar.com/s3/tour/645x430/185109_9fa46adf.jpg'}, 
{id:12, star: 4, category: "Special trip", checkbox:'specialTrip', name: 'Around the Baltic Sea by bus', duration: "38 days", date: 'July 19, 2021', price: 10295, description: 'For thousands of years the Baltic Sea has been the heart of Northern Europe and the center of the exchange of goods and knowledge, ideas and cultures - but also the scene of wars of struggle for supremacy around the Mare Balticum.', image: 'https://www.tourism.de/wp-content/uploads/2017/05/Rugen-Chalk-Coast.jpg'}, 
{id:13, star: 3, category: "Special trip", checkbox:'specialTrip', name: 'The Grand Tour of German Philosophy', duration: "15 days", date: 'September 2nd, 2021', price: 5295, description: 'Travel to explore the vast and always fascinating land of the mind: That is the idea of ​​the Grand Tour of German Philosophy, which introduces you to the most important thinkers and poets of the German language.', image: 'https://cdn.britannica.com/w:1100/42/163042-131-6AC5D943/greeting-guests-Agathon-canvas-oil-Platos-Symposium-1869.jpg'}]

export default tripsData



